### ISSUE TITLE
Settle on what our ideal template repository is

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/sphinx-lesson#21]
How do we recommend people to get started?  
a) We should have some example that is easy to copy and modify to start fresh.
b) when converting an existing lesson, there should be some minimal skeleton you can `merge --allow-unrelated-histories` to bring in all the files you need, but no more.

What we have so far:

* https://github.com/coderefinery/sphinx-lesson-template-empty
  This empty template is my latest "use this to start off".  It has no content in it, which means it is easier to merge into an existing project and do some renames.

* https://github.com/coderefinery/sphinx-lesson-template
  This started as a fork of this very repository, then it split off as a sample lesson that could be used to start off.  I think this doesn't really have a purpose anymore.

* Regarding the above two: should the template repo have sample files, or be a bare skeleton (and you copy from the primary sphinx-lesson repo, for example the [sample page](https://coderefinery.github.io/sphinx-lesson/sample-episode-rst/))?  Or do we have one template of both types?  Less is probably better.

* We also have python-for-scicomp and github-without-command-line that can serve as templates.

**Comment by bast** [comment]
Less is better. If we want to maintain less, we can have a an "empty" template and we can also point to some real lesson that we use which has grown from the template where people can see and check how this looks in real life and how to implement certain features.

**Comment by rkdarst** [comment]
I think this  i settled, the -empty one was renamed to sphinx-lesson-template and made the recommended starting point
