### ISSUE TITLE
release on PyPI

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/sphinx-lesson#22]
Right now development is very fast, so this is what is in requirements.txt:
```
https://github.com/coderefinery/sphinx-lesson/archive/master.zip
```
But we should probably release on PyPI.

* What is our version numbering strategy - do we have many small releases?
* Right now development is so fast it's useful to say "everyone work from master".  Maybe, for our own lessons for the next few months, we can keep doing that anyway?

**Comment by bast** [comment]
- I think right now following latest `master` is best until we release also the lessons.
- I would try to follow semantic versioning somehow. Maybe we can start with 0.5.0?

**Comment by rkdarst** [comment]
done (though I forgot this and started with 0.8.0)
