### ISSUE TITLE
Dropdown boxes shown by default

### ISSUE THREAD

**Issue by robertodr** [coderefinery/sphinx-lesson#47]
Is there a way to have a dropdown box whose content is shown by default?

From the code here: https://github.com/coderefinery/sphinx-lesson/blob/master/sphinx_lesson/directives.py#L70-L71 it seems I can either have the dropdown, with the contents initially hidden, or the contents shown, but no button to fold them.

**Comment by rkdarst** [comment]
This is the source of it:
https://pypi.org/project/sphinx-togglebutton/

It seems that adding `toggle-shown` to the class should make it show by default.  Those docs were wrong at one point, I think I made a PR to fix them, but it's possible there is still something a bit wrong about it.

I hope that the syntax there would let one add to any admonition, to make it shown by default, even in sphinx lesson.

**Comment by robertodr** [comment]
A-ha! Thanks for pointing out that repo! I searched around the sphinx, sphinx-rtd-theme, and docutils repos for those classes. You can achieve what I wanted with: `extra_classes = ["dropdown", "toggle-shown"]`.

![Screenshot from 2020-12-03 14-16-19](https://user-images.githubusercontent.com/3708689/101022783-24826000-3572-11eb-87a7-140b1a6a2ee9.png)
