### ISSUE TITLE
Are the symbols emojis? Or something else?

### ISSUE THREAD

**Issue by robertodr** [coderefinery/sphinx-lesson#48]
I'm trying to change the symbols in some admonitions and am using emojis. They are however not rendered, so I am wondering whether the `content` is something other than an emoji: https://github.com/coderefinery/sphinx-lesson/blob/master/sphinx_lesson/_static/sphinx_lesson.css#L19

**Comment by rkdarst** [comment]
It is an emoji, basically I have found the raw unicode character from some website, and copied that to there.  So exact rendering depends on the browser's fonts, I guess.  I also have these problems with rendering depending on how I see it.

For all emojis (and to some extent, color schemes and names), I haven't put that much thought into it, so if you think about it a bit, please submit it to us.  My considerations:
- some of the emoji colors weren't very visible.
- Apparently there are colored and uncolored versions.  I haven't fully figured this out yet.
- The box colors are inherited from sphinx_rtd_theme, and the main choice is which sphinx-lesson class inherits from which sphinx_rtd_theme class.

**Comment by robertodr** [comment]
For background: I am trying to add new directives to show function signatures and the emoji is not being rendered. If I try to copy-paste one of the emojis in the current CSS, my Emacs session freezes :smile_cat:

**Comment by robertodr** [comment]
I've succeeded by looking up the emoji no emojipedia.org, copying the codepoint, pasting it in CSS, and replacing `U+` with `\0`.

**Comment by robertodr** [comment]
And it seems one needs to stick to old-ish versions of Unicode (at least for me when building locally)

**Comment by rkdarst** [comment]
Hm, I guess it's a good idea to not use unicode that's too new, so
that it is available on as many devices as possible.  I think
emojipedia says unicode versions introduced?

**Comment by robertodr** [comment]
Yes, they list when the emoji was introduced.
