### ISSUE TITLE
Wrong link in PyP

### ISSUE THREAD

**Issue by chepo92** [coderefinery/sphinx-lesson#69]
In https://pypi.org/project/sphinx-lesson/

Homepage says 
https://github.com/coderefinery/sphinx_lesson  (notice underscore)
Should be
https://github.com/coderefinery/sphinx-lesson

**Comment by bast** [comment]
Probably solved by #70 but we should keep this open until a new version is published on PyPI.

**Comment by rkdarst** [comment]
I released a new version, so this is updated now.  Thanks for the report!
