### ISSUE TITLE
cssname method now missing

### ISSUE THREAD

**Issue by mabraham** [coderefinery/sphinx-lesson#71]
I believe this change (https://github.com/coderefinery/sphinx-lesson/commit/d7ff66e583437455b1c6b547f598fbc53a2aa60d#diff-de1821ead97ff0f20a56e28dadb88a529ada12b5fb085a3b98e202274f64ddceR38) broke downstream code like at https://github.com/ENCCS/openmp-gpu/blob/7672ede569a08d0a4429c99e5cdb75b97ae41682/content/conf.py#L128

Can we re-introduce a `cssname` method that calls `get_cssname` so that we don't have to find and fix all such repos, please? Or should we be handling directives differently?

**Comment by rkdarst** [comment]
I guess people have started to use internals faster than I thought!  Backwards compatibilty is very important to me, so it would be good to support this (or at least give a longer transition period...).  I added it back here:
  https://github.com/coderefinery/sphinx-lesson/pull/72
I'm wondering if I should say "too late" and just completely revert that change...

Do you want to confirm this change is OK?

I guess I need to make a release after this.
